/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './message';
import * as i2 from '@angular/common';
export const MessageModuleNgFactory:i0.NgModuleFactory<i1.MessageModule> = i0.ɵcmf(i1.MessageModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.MessageModule,i1.MessageModule,
          ([] as any[]))]);
    });
const styles_UIMessage:any[] = ([] as any[]);
export const RenderType_UIMessage:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_UIMessage,
    data:{}});
function View_UIMessage_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),9,'div',[['aria-live',
      'polite'],['class','ui-message ui-widget ui-corner-all']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),i0.ɵdid(278528,(null as any),0,i2.NgClass,
      [i0.IterableDiffers,i0.KeyValueDiffers,i0.ElementRef,i0.Renderer],{klass:[0,
          'klass'],ngClass:[1,'ngClass']},(null as any)),i0.ɵpod({'ui-messages-info':0,
      'ui-messages-warn':1,'ui-messages-error':2,'ui-messages-success':3}),(_l()(),
      i0.ɵted((null as any),['\n            '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      1,'span',[['class','ui-message-icon']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),i0.ɵdid(278528,(null as any),0,i2.NgClass,[i0.IterableDiffers,
      i0.KeyValueDiffers,i0.ElementRef,i0.Renderer],{klass:[0,'klass'],ngClass:[1,
      'ngClass']},(null as any)),(_l()(),i0.ɵted((null as any),['\n            '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'span',[['class','ui-message-text']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['',''])),(_l()(),i0.ɵted((null as any),['\n        ']))],
      (_ck,_v) => {
        var _co:any = _v.component;
        const currVal_0:any = 'ui-message ui-widget ui-corner-all';
        const currVal_1:any = _ck(_v,2,0,(_co.severity === 'info'),(_co.severity === 'warn'),
            (_co.severity === 'error'),(_co.severity === 'success'));
        _ck(_v,1,0,currVal_0,currVal_1);
        const currVal_2:any = 'ui-message-icon';
        const currVal_3:any = _co.icon;
        _ck(_v,5,0,currVal_2,currVal_3);
      },(_ck,_v) => {
        var _co:any = _v.component;
        const currVal_4:any = _co.text;
        _ck(_v,8,0,currVal_4);
      });
}
export function View_UIMessage_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵand(16777216,
      (null as any),(null as any),1,(null as any),View_UIMessage_1)),i0.ɵdid(16384,
      (null as any),0,i2.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,'ngIf']},
      (null as any)),(_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,_v) => {
    var _co:i1.UIMessage = _v.component;
    const currVal_0:any = _co.severity;
    _ck(_v,2,0,currVal_0);
  },(null as any));
}
export function View_UIMessage_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p-message',([] as any[]),
      (null as any),(null as any),(null as any),View_UIMessage_0,RenderType_UIMessage)),
      i0.ɵdid(49152,(null as any),0,i1.UIMessage,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const UIMessageNgFactory:i0.ComponentFactory<i1.UIMessage> = i0.ɵccf('p-message',
    i1.UIMessage,View_UIMessage_Host_0,{severity:'severity',text:'text'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZGV2ZWxvcG1lbnQvcHJpbWVmYWNlcy9wcmltZW5nL3NyYy9hcHAvY29tcG9uZW50cy9tZXNzYWdlL21lc3NhZ2UubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9kZXZlbG9wbWVudC9wcmltZWZhY2VzL3ByaW1lbmcvc3JjL2FwcC9jb21wb25lbnRzL21lc3NhZ2UvbWVzc2FnZS50cyIsIm5nOi8vL2hvbWUvZGV2ZWxvcG1lbnQvcHJpbWVmYWNlcy9wcmltZW5nL3NyYy9hcHAvY29tcG9uZW50cy9tZXNzYWdlL21lc3NhZ2UudHMuVUlNZXNzYWdlLmh0bWwiLCJuZzovLy9ob21lL2RldmVsb3BtZW50L3ByaW1lZmFjZXMvcHJpbWVuZy9zcmMvYXBwL2NvbXBvbmVudHMvbWVzc2FnZS9tZXNzYWdlLnRzLlVJTWVzc2FnZV9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGFyaWEtbGl2ZT1cInBvbGl0ZVwiIGNsYXNzPVwidWktbWVzc2FnZSB1aS13aWRnZXQgdWktY29ybmVyLWFsbFwiICpuZ0lmPVwic2V2ZXJpdHlcIlxuICAgICAgICBbbmdDbGFzc109XCJ7J3VpLW1lc3NhZ2VzLWluZm8nOiAoc2V2ZXJpdHkgPT09ICdpbmZvJyksXG4gICAgICAgICAgICAgICAgJ3VpLW1lc3NhZ2VzLXdhcm4nOiAoc2V2ZXJpdHkgPT09ICd3YXJuJyksXG4gICAgICAgICAgICAgICAgJ3VpLW1lc3NhZ2VzLWVycm9yJzogKHNldmVyaXR5ID09PSAnZXJyb3InKSxcbiAgICAgICAgICAgICAgICAndWktbWVzc2FnZXMtc3VjY2Vzcyc6IChzZXZlcml0eSA9PT0gJ3N1Y2Nlc3MnKX1cIj5cbiAgICAgICAgICAgIDxzcGFuIGNsYXNzPVwidWktbWVzc2FnZS1pY29uXCIgW25nQ2xhc3NdPVwiaWNvblwiPjwvc3Bhbj5cbiAgICAgICAgICAgIDxzcGFuIGNsYXNzPVwidWktbWVzc2FnZS10ZXh0XCI+e3t0ZXh0fX08L3NwYW4+XG4gICAgICAgIDwvZGl2PlxuICAgICIsIjxwLW1lc3NhZ2U+PC9wLW1lc3NhZ2U+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQ1E7TUFBQTtNQUFBLG1EQUFBO01BQUE7VUFBQSxzREFDQTtNQUFBLHFFQUcwRDthQUFBLG9DQUN0RDtNQUFBO01BQUEscUNBQUE7a0RBQUE7TUFBQSwyQkFBc0Q7TUFDdEQ7VUFBQTtNQUE4Qix3Q0FBZTs7O1FBTnpCO1FBQ3hCO1lBQUE7UUFEQSxXQUF3QixVQUN4QixTQURBO1FBS1U7UUFBd0I7UUFBOUIsV0FBTSxVQUF3QixTQUE5Qjs7O1FBQzhCO1FBQUE7Ozs7b0JBUDFDLCtDQUNRO01BQUEsc0VBQUE7TUFBQTtNQUFBLGVBT007O0lBUDZEO0lBQW5FLFdBQW1FLFNBQW5FOzs7O29CQ0RSO01BQUE7YUFBQTs7OzsifQ==
