/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './progressspinner';
import * as i2 from '@angular/common';
export const ProgressSpinnerModuleNgFactory:i0.NgModuleFactory<i1.ProgressSpinnerModule> = i0.ɵcmf(i1.ProgressSpinnerModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.ProgressSpinnerModule,i1.ProgressSpinnerModule,
          ([] as any[]))]);
    });
const styles_ProgressSpinner:any[] = ([] as any[]);
export const RenderType_ProgressSpinner:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ProgressSpinner,data:{}});
export function View_ProgressSpinner_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),8,'div',[['class','ui-progress-spinner']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),i0.ɵdid(278528,(null as any),
      0,i2.NgClass,[i0.IterableDiffers,i0.KeyValueDiffers,i0.ElementRef,i0.Renderer],
      {klass:[0,'klass'],ngClass:[1,'ngClass']},(null as any)),i0.ɵdid(278528,(null as any),
      0,i2.NgStyle,[i0.KeyValueDiffers,i0.ElementRef,i0.Renderer],{ngStyle:[0,'ngStyle']},
      (null as any)),(_l()(),i0.ɵted((null as any),['\n            '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),3,':svg:svg',[['class','ui-progress-spinner-svg'],
          ['viewBox','25 25 50 50']],[[4,'animation-duration',(null as any)]],(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n                '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),0,':svg:circle',[['class','ui-progress-spinner-circle'],
          ['cx','50'],['cy','50'],['r','20'],['stroke-miterlimit','10']],[[1,'fill',
          0],[1,'stroke-width',0]],(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n            '])),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,_v) => {
    var _co:i1.ProgressSpinner = _v.component;
    const currVal_0:any = 'ui-progress-spinner';
    const currVal_1:any = _co.styleClass;
    _ck(_v,2,0,currVal_0,currVal_1);
    const currVal_2:any = _co.style;
    _ck(_v,3,0,currVal_2);
  },(_ck,_v) => {
    var _co:i1.ProgressSpinner = _v.component;
    const currVal_3:any = _co.animationDuration;
    _ck(_v,5,0,currVal_3);
    const currVal_4:any = _co.fill;
    const currVal_5:any = _co.strokeWidth;
    _ck(_v,7,0,currVal_4,currVal_5);
  });
}
export function View_ProgressSpinner_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p-progressSpinner',
      ([] as any[]),(null as any),(null as any),(null as any),View_ProgressSpinner_0,
      RenderType_ProgressSpinner)),i0.ɵdid(49152,(null as any),0,i1.ProgressSpinner,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ProgressSpinnerNgFactory:i0.ComponentFactory<i1.ProgressSpinner> = i0.ɵccf('p-progressSpinner',
    i1.ProgressSpinner,View_ProgressSpinner_Host_0,{style:'style',styleClass:'styleClass',
        strokeWidth:'strokeWidth',fill:'fill',animationDuration:'animationDuration'},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZGV2ZWxvcG1lbnQvcHJpbWVmYWNlcy9wcmltZW5nL3NyYy9hcHAvY29tcG9uZW50cy9wcm9ncmVzc3NwaW5uZXIvcHJvZ3Jlc3NzcGlubmVyLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvZGV2ZWxvcG1lbnQvcHJpbWVmYWNlcy9wcmltZW5nL3NyYy9hcHAvY29tcG9uZW50cy9wcm9ncmVzc3NwaW5uZXIvcHJvZ3Jlc3NzcGlubmVyLnRzIiwibmc6Ly8vaG9tZS9kZXZlbG9wbWVudC9wcmltZWZhY2VzL3ByaW1lbmcvc3JjL2FwcC9jb21wb25lbnRzL3Byb2dyZXNzc3Bpbm5lci9wcm9ncmVzc3NwaW5uZXIudHMuUHJvZ3Jlc3NTcGlubmVyLmh0bWwiLCJuZzovLy9ob21lL2RldmVsb3BtZW50L3ByaW1lZmFjZXMvcHJpbWVuZy9zcmMvYXBwL2NvbXBvbmVudHMvcHJvZ3Jlc3NzcGlubmVyL3Byb2dyZXNzc3Bpbm5lci50cy5Qcm9ncmVzc1NwaW5uZXJfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgPGRpdiBjbGFzcz1cInVpLXByb2dyZXNzLXNwaW5uZXJcIiBbbmdTdHlsZV09XCJzdHlsZVwiIFtuZ0NsYXNzXT1cInN0eWxlQ2xhc3NcIj5cbiAgICAgICAgICAgIDxzdmcgY2xhc3M9XCJ1aS1wcm9ncmVzcy1zcGlubmVyLXN2Z1wiIHZpZXdCb3g9XCIyNSAyNSA1MCA1MFwiIFtzdHlsZS5hbmltYXRpb24tZHVyYXRpb25dPVwiYW5pbWF0aW9uRHVyYXRpb25cIj5cbiAgICAgICAgICAgICAgICA8Y2lyY2xlIGNsYXNzPVwidWktcHJvZ3Jlc3Mtc3Bpbm5lci1jaXJjbGVcIiBjeD1cIjUwXCIgY3k9XCI1MFwiIHI9XCIyMFwiIFthdHRyLmZpbGxdPVwiZmlsbFwiIFthdHRyLnN0cm9rZS13aWR0aF09XCJzdHJva2VXaWR0aFwiIHN0cm9rZS1taXRlcmxpbWl0PVwiMTBcIi8+XG4gICAgICAgICAgICA8L3N2Zz5cbiAgICAgICAgPC9kaXY+XG4gICAgIiwiPHAtcHJvZ3Jlc3NTcGlubmVyPjwvcC1wcm9ncmVzc1NwaW5uZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsK0NBQ1E7TUFBQTtNQUFBLGlFQUFBO01BQUE7TUFBQSxnRUFBQTtNQUFBO01BQUEsZUFBMEUsbURBQ3RFO01BQUE7VUFBQTtNQUFBLDRDQUEwRztNQUN0RztVQUFBO1VBQUE7TUFBK0ksbURBQzdJO1VBQUEsaUJBQ0o7O0lBSkQ7SUFBOEM7SUFBbkQsV0FBSyxVQUE4QyxTQUFuRDtJQUFpQztJQUFqQyxXQUFpQyxTQUFqQzs7O0lBQytEO0lBQTNELFdBQTJELFNBQTNEO0lBQ3NFO0lBQW1CO0lBQXJGLFdBQWtFLFVBQW1CLFNBQXJGOzs7O29CQ0hoQjtNQUFBO2dDQUFBLFVBQUE7TUFBQTs7Ozs7In0=
